### ISSUE TITLE
help

### ISSUE THREAD

**Issue by 123zyp** [LingLi28/PDPTW#1]
Hello, may I ask if there are any papers or documents describing the relevant issues? If so, please share them with my email 785282983@qq.com Thank you for sharing

**Comment by LingLi28** [comment]
Hi, thank you for your interest. I can share some literature with you. But I think you can download by yourself.

**Comment by 123zyp** [comment]
First of all, thank you for your reply.  I look forward to your sharing of relevant literature.  I have been studying your code for the past two days and have found it very helpful for my future studies.
