### ISSUE TITLE
代码运行结果

### ISSUE THREAD

**Issue by GTYGTY123456** [LingLi28/PDPTW#3]
你好，代码在运行完之后没有显示具体的车辆路径，请教一下是在编写的时候没有写吗，感谢回答

**Comment by LingLi28** [comment]
你好，谢谢你的提问，具体的车辆路径信息应该是在的，但需要自行添加一下打印输出的代码。

**Comment by GTYGTY123456** [comment]
收到，感谢你的回复，我先自己试一试，感谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Li Ling ***@***.***&gt;; 
发送时间: 2024年10月28日(星期一) 晚上6:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LingLi28/PDPTW] 代码运行结果 (Issue #3)














 
你好，谢谢你的提问，具体的车辆路径信息应该是在的，但需要自行添加一下打印输出的代码。

**Comment by LingLi28** [comment]
不客气，加油
